NeveraPortal.UI/Areas/Admin/Models/Country/CreateCountryVM.cs
using System.ComponentModel.DataAnnotations;

namespace NeveraPortal.UI.Areas.Admin.Models.Country
{
    public class CreateCountryVM
    {
        [Required]
        public string Name { get; set; }
    }
}

NeveraPortal.UI/Areas/Admin/Models/Country/EditCountryVM.cs
using System.ComponentModel.DataAnnotations;

namespace NeveraPortal.UI.Areas.Admin.Models.Country
{
	public class EditCountryVM
	{

		public int Id { get; set; }
		[Required]
		public string Name { get; set; }
	}
}

NeveraPortal.UI/Areas/Admin/Models/Country/IndexCountryVM.cs
using System.ComponentModel.DataAnnotations;

namespace NeveraPortal.UI.Areas.Admin.Models.Country
{
	public class IndexCountryVM
	{
        public int Id { get; set; }
		public string Name { get; set; }
		[DataType(DataType.DateTime)]
		public DateTime AddDate { get; set; }

		[DataType(DataType.DateTime)]
		public DateTime UpdateDate { get; set; }
	}
}

NeveraPortal.UI/Areas/Admin/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FirebaseTest.Bussiness;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NeveraPortal.BLL.Services.Interfaces;
using NeveraPortal.BLL.Services.Repositories;
using NeveraPortal.DAL.Models;
using NeveraPortal.UI.Areas.Admin.Models.AdminUser;
using NeveraPortal.UI.Areas.Admin.Models.Blog;
using NeveraPortal.UI.Areas.Admin.Models.Country;

namespace NeveraPortal.UI.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class CountryController : Controller
    {
        private readonly ICountryRepository _countryRepository;

        public CountryController(ICountryRepository countryRepository)
        {
            _countryRepository = countryRepository;
        }

        public IActionResult Index()
        {
            var countries = _countryRepository.GetAll();
            return View(countries);
        }

		public IActionResult Create()
		{
			return View();
		}

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(CreateCountryVM model)
        {
            if (ModelState.IsValid)
            {
                Country country = new Country();
                country.Name = model.Name;
                

                _countryRepository.Create(country);
                return Redirect("~/admin/country/");
            }
            else
            {
                return View(model);
            }

        }
		public async Task<IActionResult> Delete(int id)
		{

			
			var result = _countryRepository.Delete(id);
			if (result == null)
			{
				return NotFound();
			}
			return Redirect("/Admin/Country/index");
		}

		public IActionResult Edit(int id)
		{
			var country = _countryRepository.GetById(id);
			if (country == null)
			{
				ViewBag.Error = "Something went wrong and country couldnt found";
				return View();
			}
			var model = new EditCountryVM
			{
				Id = country.Id,
				Name = country.Name,
			};
			return View(model);
		}
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(EditCountryVM model)
        {
            if (ModelState.IsValid)
            {
                Country country = _countryRepository.GetById(model.Id);

                if (country == null)
                {
                    ViewBag.Error = "Something went wrong and country could not be found.";
                    return View(model);
                }

                country.Name = model.Name;

                _countryRepository.Update(country);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }





    }
}

NeveraPortal.UI/Areas/Admin/Views/Country/Create.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
@model CreateCountryVM

<h1>Create</h1>

<hr />

<form action="/admin/country/create" method="post" id="createForm">
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label class="control-label">Name</label>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
    <button type="button" class="btn btn-secondary" onclick="cancel()">Cancel</button>
</form>

<script>
    function cancel() {
        history.back();
    }
</script>

NeveraPortal.UI/Areas/Admin/Views/Country/Edit.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
@model EditCountryVM

<h1>Edit Country</h1>

<hr />

<form method="post" asp-action="Edit" asp-controller="Country" id="createForm">
    <input type="hidden" asp-for="Id" />
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label class="control-label">Country</label>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
    <button type="button" class="btn btn-secondary" onclick="cancel()">Cancel</button>
</form>

<script>
    function cancel() {
        history.back();
    }
</script>

NeveraPortal.UI/Areas/Admin/Views/Country/Index.cshtml
@model List<Country>﻿
@using NonFactors.Mvc.Grid;
@{
	Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<div class="float-right">
    <a class="btn btn-success my-2" href="/admin/country/create">Create Country</a>
</div>

<h1>Countriest</h1>
<form action="/admin/country" method="post">

	@Html.AntiForgeryToken()
	@(Html
		.Grid(Model)
		.Build(columns =>
		{

			columns.Add(model => model.Id).Titled("Id");
			columns.Add(model => model.Name).Titled("Country Name");
			columns.Add(model => $"<a class=\"btn btn-primary\"  href=\"/admin/country/edit/{model.Id}\">Update</a>").Encoded(false);
			columns.Add(model => $"<a class=\"btn btn-danger\" href=\"/admin/country/delete/{model.Id}\">Delete</a>").Encoded(false);
		})
		)

</form>