NeveraPortal.UI/Areas/Admin/Models/AdminUser/CreateAdminUserVM.cs
using System.ComponentModel.DataAnnotations;

namespace NeveraPortal.UI.Areas.Admin.Models.AdminUser
{
    public class CreateAdminUserVM
    {
        [Required]
        [EmailAddress(ErrorMessage = "Enter an email address in valid format")]
        public string EMail { get; set; } = string.Empty;

        [Required]
        [StringLength(100, ErrorMessage = "The password must be at least {2} characters.", MinimumLength = 6)]
        public string Password { get; set; } = string.Empty;

        [Required, Compare(nameof(Password))]
        public string ConfirmPassword { get; set; } = string.Empty;
    }
}

NeveraPortal.UI/Areas/Admin/Models/AdminUser/EditAdminUserVM.cs
using System.ComponentModel.DataAnnotations;

namespace NeveraPortal.UI.Areas.Admin.Models.AdminUser
{
    public class EditAdminUserVM
    {
        public int Id { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Enter an email address in valid format")]
        public string EMail { get; set; } = string.Empty;

        [Required]
        [StringLength(100, ErrorMessage = "The password must be at least {2} characters.", MinimumLength = 6)]
        public string Password { get; set; } = string.Empty;

        [Required, Compare(nameof(Password))]
        public string ConfirmPassword { get; set; } = string.Empty;
    }
}

NeveraPortal.UI/Areas/Admin/Models/AdminUser/IndexAdminUserVM.cs
using System.ComponentModel.DataAnnotations;

namespace NeveraPortal.UI.Areas.Admin.Models.AdminUser
{
    public class IndexAdminUserVM
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "EMail")]
        [DataType(DataType.EmailAddress)]
        public string EMail { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime AddDate { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime UpdateDate { get; set; }

    }
}

NeveraPortal.UI/Areas/Admin/Controllers/AdminUserController.cs
using Microsoft.AspNetCore.Mvc;
using NeveraPortal.BLL.Services.Repositories;
using NeveraPortal.DAL.Models;
using NeveraPortal.UI.Areas.Admin.Models.AdminUser;

namespace NeveraPortal.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminUserController : Controller
    {
        GenericRepository<AdminUser> _adminUserRepository;
        public AdminUserController() {

            _adminUserRepository = new GenericRepository<AdminUser>();
        }

        public IActionResult Index()
        {
            List<IndexAdminUserVM> model = new List<IndexAdminUserVM>();
            model = _adminUserRepository.GetAll().Select(x => new IndexAdminUserVM
            {
                Id = x.Id,
                EMail = x.EMail,
                AddDate = x.AddDate,
                UpdateDate = x.UpdateDate,

            }).ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(CreateAdminUserVM model)
        {
            if (ModelState.IsValid)
            {
                AdminUser adminUser = new AdminUser();
                adminUser.EMail = model.EMail;
                adminUser.Password = model.Password;

                _adminUserRepository.Create(adminUser);
                return Redirect("~/admin/adminuser/");
            }
            else
            {
                return View(model);
            }
            
        }

        public IActionResult Edit(int id)
        {
            AdminUser user = _adminUserRepository.GetById(id);

            if (user == null)
            {
                return NotFound(); 
            }

            EditAdminUserVM model = new EditAdminUserVM
            {
                Id = user.Id,
                EMail = user.EMail,
     
            };

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(EditAdminUserVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    AdminUser userToUpdate = _adminUserRepository.GetById(model.Id);

                    if (userToUpdate == null)
                    {
                        return NotFound(); 
                    }

                    userToUpdate.EMail = model.EMail;

                    _adminUserRepository.Update(userToUpdate);

                    return Redirect("~/admin/adminuser/");
                }
                catch (Exception ex)
                {
                    return View("Error"); 
                }
            }
            else
            {
                return View(model);
            }
        }



        public IActionResult Delete(int id)
		{

			AdminUser user = _adminUserRepository.GetById(id);

			if (user == null)
			{
				return NotFound(); 
			}


			_adminUserRepository.Delete(id);

			return Redirect("~/admin/adminuser/");
		}



	}
}

NeveraPortal.UI/Areas/Admin/Views/AdminUser/Create.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model NeveraPortal.UI.Areas.Admin.Models.AdminUser.CreateAdminUserVM

<h1>Create User</h1>

<hr />

<form action="/admin/adminuser/create" method="post" id="createForm">
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label class="control-label">EMail</label>
        @Html.TextBoxFor(m => m.EMail, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label class="control-label">Password</label>
        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label class="control-label">ConfirmPassword</label>
        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
    <button type="button" class="btn btn-secondary" onclick="cancel()">Cancel</button>
</form>

<script>
    function cancel() {
        history.back();
    }
</script>

NeveraPortal.UI/Areas/Admin/Views/AdminUser/Edit.cshtml
@model NeveraPortal.UI.Areas.Admin.Models.AdminUser.EditAdminUserVM
@{
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@{
    ViewData["Title"] = "Edit User";
}

<h1>Edit User</h1>

<hr />

<form method="post" asp-action="Edit" asp-controller="AdminUser" id="createForm">
    <input type="hidden" asp-for="Id" />
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@error.ErrorMessage</li>
                }
            </ul>
        </div>
    }
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label class="control-label">EMail</label>
        @Html.TextBoxFor(m => m.EMail, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label class="control-label">Password</label>
        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label class="control-label">ConfirmPassword</label>
        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
    <button type="button" class="btn btn-secondary" onclick="cancel()">Cancel</button>
</form>

<script>
    function cancel() {
        history.back();
    }
</script>

NeveraPortal.UI/Areas/Admin/Views/AdminUser/Index.cshtml
@using NonFactors.Mvc.Grid;
@{
	Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model List<NeveraPortal.UI.Areas.Admin.Models.AdminUser.IndexAdminUserVM>

<h1>AdminUsers</h1>

<div class="d-flex justify-content-end">
	<a class="btn btn-success my-2" href="/admin/adminuser/create">Create AdminUser</a>
</div>

<form action="/admin/adminuser" method="post">

	@Html.AntiForgeryToken()
	@(Html
		.Grid(Model)
		.Build(columns =>
		{

			columns.Add(model => model.Id).Titled("Id");
			columns.Add(model => model.EMail).Titled("EMail");
			columns.Add(model => $"<a class=\"btn btn-primary\"  href=\"/admin/adminuser/edit/{model.Id}\">Update</a>").Encoded(false);
			columns.Add(model => $"<a class=\"btn btn-danger\" href=\"/admin/adminuser/delete/{model.Id}\">Delete</a>").Encoded(false);



		})
		)

</form>